baseurl = "/"
languageCode = "en-us"
title = "AO"
theme = "hugo-theme-casper"
disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10
canonifyurls = true

[params]
  description = "AO - the online electricals store. Incredible deals, free delivery and price match on the best range of washing machines, fridge freezers, laptops and more."
  cover = "images/cover.jpg"
  author = "AO"
  authorlocation = "Manchester, England"
  authorwebsite = "http://aohackathon.netlify.com"
  bio= "my bio"
  logo = "images/logo.png"
  googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  githubName = "Malefis"
  twitterName = "ao_jobs"
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = true
  [params.social]
    twitter = "ao_jobs"
